
package frc.robot.Autonomous.ChoreoTrajectories;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj CenterDepot = new ChoreoTraj(
	    "CenterDepot",
	    OptionalInt.empty(),
	    5.28494,
	    new Pose2d(3.554, 4.035, Rotation2d.fromRadians(3.142)),
	    new Pose2d(2, 3.833, Rotation2d.fromRadians(-1.571))
	);
	public static final ChoreoTraj CenterScore8 = new ChoreoTraj(
	    "CenterScore8",
	    OptionalInt.empty(),
	    2.00492,
	    new Pose2d(3.587, 3.833, Rotation2d.fromRadians(0)),
	    new Pose2d(1.696, 3.833, Rotation2d.fromRadians(-1.564))
	);
	public static final ChoreoTraj CenterScoreToClimb = new ChoreoTraj(
	    "CenterScoreToClimb",
	    OptionalInt.empty(),
	    1.83032,
	    new Pose2d(2, 3.833, Rotation2d.fromRadians(-1.571)),
	    new Pose2d(0.698, 4.623, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj Drive1 = new ChoreoTraj(
	    "Drive1",
	    OptionalInt.empty(),
	    1.50695,
	    new Pose2d(0.5, 2, Rotation2d.fromRadians(0)),
	    new Pose2d(1.5, 1, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj Left2Cycle_P1 = new ChoreoTraj(
	    "Left2Cycle_P1",
	    OptionalInt.empty(),
	    5.96659,
	    new Pose2d(3.585, 7.519, Rotation2d.fromRadians(0)),
	    new Pose2d(2.521, 7.233, Rotation2d.fromRadians(-2.613))
	);
	public static final ChoreoTraj Left2Cycle_P2 = new ChoreoTraj(
	    "Left2Cycle_P2",
	    OptionalInt.empty(),
	    7.81574,
	    new Pose2d(2.521, 7.233, Rotation2d.fromRadians(-2.613)),
	    new Pose2d(2.521, 7.233, Rotation2d.fromRadians(-2.613))
	);
	public static final ChoreoTraj Left2Cycle_P3 = new ChoreoTraj(
	    "Left2Cycle_P3",
	    OptionalInt.empty(),
	    2.61762,
	    new Pose2d(2.521, 7.233, Rotation2d.fromRadians(-2.613)),
	    new Pose2d(7.263, 6.224, Rotation2d.fromRadians(-1.153))
	);
	public static final ChoreoTraj Right1CycleDepot = new ChoreoTraj(
	    "Right1CycleDepot",
	    OptionalInt.empty(),
	    7.27176,
	    new Pose2d(4.412, 0.451, Rotation2d.fromRadians(0)),
	    new Pose2d(0.581, 0.48, Rotation2d.fromRadians(1.571))
	);
	public static final ChoreoTraj Right2Cycle_P1 = new ChoreoTraj(
	    "Right2Cycle_P1",
	    OptionalInt.empty(),
	    5.85446,
	    new Pose2d(3.585, 0.551, Rotation2d.fromRadians(0)),
	    new Pose2d(2.521, 0.837, Rotation2d.fromRadians(-0.634))
	);
	public static final ChoreoTraj Right2Cycle_P2 = new ChoreoTraj(
	    "Right2Cycle_P2",
	    OptionalInt.empty(),
	    7.45412,
	    new Pose2d(2.521, 0.837, Rotation2d.fromRadians(-0.634)),
	    new Pose2d(2.521, 0.837, Rotation2d.fromRadians(-0.634))
	);
	public static final ChoreoTraj Right2Cycle_P3 = new ChoreoTraj(
	    "Right2Cycle_P3",
	    OptionalInt.empty(),
	    1.64928,
	    new Pose2d(2.521, 0.837, Rotation2d.fromRadians(-0.634)),
	    new Pose2d(7.263, 1.846, Rotation2d.fromRadians(1.153))
	);
	public static final ChoreoTraj SweeperLeft1Cycle_P1 = new ChoreoTraj(
	    "SweeperLeft1Cycle_P1",
	    OptionalInt.empty(),
	    6.3876,
	    new Pose2d(3.585, 7.519, Rotation2d.fromRadians(0)),
	    new Pose2d(2.521, 0.837, Rotation2d.fromRadians(-0.634))
	);
	public static final ChoreoTraj SweeperLeft1Cycle_P2 = new ChoreoTraj(
	    "SweeperLeft1Cycle_P2",
	    OptionalInt.empty(),
	    4.97561,
	    new Pose2d(2.521, 0.837, Rotation2d.fromRadians(-0.555)),
	    new Pose2d(2.521, 0.837, Rotation2d.fromRadians(-0.634))
	);
	public static final ChoreoTraj SweeperRight1Cycle_P1 = new ChoreoTraj(
	    "SweeperRight1Cycle_P1",
	    OptionalInt.empty(),
	    6.38763,
	    new Pose2d(3.585, 0.551, Rotation2d.fromRadians(0)),
	    new Pose2d(2.521, 7.233, Rotation2d.fromRadians(-2.613))
	);
	public static final ChoreoTraj SweeperRight1Cycle_P2 = new ChoreoTraj(
	    "SweeperRight1Cycle_P2",
	    OptionalInt.empty(),
	    4.9822,
	    new Pose2d(2.521, 7.233, Rotation2d.fromRadians(-2.5)),
	    new Pose2d(2.521, 7.233, Rotation2d.fromRadians(-2.613))
	);
    public static final ChoreoTraj RightBump2Cycle = new ChoreoTraj(
        "RightBump2Cycle",
        OptionalInt.empty(),
        6.79898,
        new Pose2d(1.90294, 3.82433, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(1.90294, 3.82433, Rotation2d.fromRadians(-1.5708))
    );

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("CenterDepot", CenterDepot),
		Map.entry("CenterScore8", CenterScore8),
		Map.entry("CenterScoreToClimb", CenterScoreToClimb),
		Map.entry("Drive1", Drive1),
		Map.entry("Left2Cycle_P1", Left2Cycle_P1),
		Map.entry("Left2Cycle_P2", Left2Cycle_P2),
		Map.entry("Left2Cycle_P3", Left2Cycle_P3),
		Map.entry("Right1CycleDepot", Right1CycleDepot),
		Map.entry("Right2Cycle_P1", Right2Cycle_P1),
		Map.entry("Right2Cycle_P2", Right2Cycle_P2),
		Map.entry("Right2Cycle_P3", Right2Cycle_P3),
		Map.entry("SweeperLeft1Cycle_P1", SweeperLeft1Cycle_P1),
		Map.entry("SweeperLeft1Cycle_P2", SweeperLeft1Cycle_P2),
		Map.entry("SweeperRight1Cycle_P1", SweeperRight1Cycle_P1),
		Map.entry("SweeperRight1Cycle_P2", SweeperRight1Cycle_P2),
        Map.entry("RightBump2Cycle", RightBump2Cycle)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
